# Generated by Django 6.0 on 2025-12-30 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0004_imagepalette_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepalette',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
