# Generated by Django 6.0 on 2025-12-30 10:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0006_extractusage'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='extractusage',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='extractusage',
            name='last_used',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='extractusage',
            name='date',
        ),
    ]
