# Generated by Django 6.0 on 2026-01-17 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0007_alter_extractusage_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'Color'},
        ),
        migrations.AlterModelOptions(
            name='extractusage',
            options={'verbose_name': 'Limit'},
        ),
        migrations.AlterModelOptions(
            name='imagepalette',
            options={'verbose_name': 'ImagePalette'},
        ),
        migrations.AlterModelOptions(
            name='palette',
            options={'verbose_name': 'Palette'},
        ),
        migrations.AddField(
            model_name='color',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Название цвета'),
        ),
        migrations.AlterField(
            model_name='color',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='color',
            name='hex_code',
            field=models.CharField(max_length=7, verbose_name='Hex-код'),
        ),
        migrations.AlterField(
            model_name='color',
            name='palette',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='apiapp.palette', verbose_name='Палитра'),
        ),
        migrations.AlterField(
            model_name='extractusage',
            name='count',
            field=models.IntegerField(default=0, verbose_name='Счетчик использований'),
        ),
        migrations.AlterField(
            model_name='extractusage',
            name='last_used',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Последнее использование'),
        ),
        migrations.AlterField(
            model_name='extractusage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='imagepalette',
            name='colors',
            field=models.JSONField(verbose_name='Извлеченные цвета'),
        ),
        migrations.AlterField(
            model_name='imagepalette',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='imagepalette',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='imagepalette',
            name='image_name',
            field=models.CharField(max_length=100, verbose_name='Название изображения'),
        ),
        migrations.AlterField(
            model_name='imagepalette',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='imagepalette',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Превью'),
        ),
        migrations.AlterField(
            model_name='palette',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='palette',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='palette',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название палитры'),
        ),
        migrations.AlterField(
            model_name='palette',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
    ]
