# Generated by Django 6.0 on 2026-01-18 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0008_alter_color_options_alter_extractusage_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='name',
        ),
    ]
